### ISSUE TITLE
Feature request - Sparse Google AD sponsors

### ISSUE THREAD

**Issue by changkaifu-houzz** [drobnikj/crawler-google-places#105]
Differentiate if stores/ companies on Google Maps are tagged with Google Ad sponsor.
One image example is pasted below 

<img width="934" alt="Screen Shot 2021-01-19 at 8 11 56 PM" src="https://user-images.githubusercontent.com/76979476/105845042-210cd180-6015-11eb-9e76-54280b86a4f1.png">

**Comment by metalwarrior665** [comment]
Currently implemented in beta, coming to latest in upcoming days

**Comment by metalwarrior665** [comment]
Has been added few days after my last comment
