### ISSUE TITLE
Need to capture the rest of available data on each place

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#11]
We need this for one customer, namely, these are:

`isAd`: true/false depending if the place has "Ad" sign
`rank`: Index on the search page, starting at 1
`socialLinks`
`webResults`
`peopleAlsoSearch`: `[{ url, title, totalScore }]`

**Comment by drobnikj** [comment]
It was done, except isAd, it doesn't work in scraper.
