### ISSUE TITLE
Error: Operation failed: Reviews extraction.

### ISSUE THREAD

**Issue by patrickredo** [drobnikj/crawler-google-places#112]
Hi, im facing this error when trying to extract places in brazillian portuguese(pt-br), 

> ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/search/?api=1&query=farmacia&query_place_id=ChIJcarikd7_zpQRAmu0KQry1ic&hl=pt","retryCount":1,"id":"NX5TKqZ87c3HtFS"}
>   Error: Operation failed: Reviews extraction. Error detail: E_MISSING_BUNDLE: {"locale":"pt"}
>       at createError (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/cldrjs/dist/cldr.js:343:11)
>       at validate (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/cldrjs/dist/cldr.js:359:10)
>       at Cldr.main (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/cldrjs/dist/cldr.js:673:3)
>       at numberNumberingSystem (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/globalize/dist/globalize/number.js:121:14)
>       at numberPattern (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/globalize/dist/globalize/number.js:1073:37)
>       at Globalize.numberParser.Globalize.numberParser (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/globalize/dist/globalize/number.js:1644:13)
>       at module.exports.extractReviews (/home/gmc/Área de Trabalho/crawler-google-places/src/extractors.js:284:42)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:97:5)
>       at async ErrorSnapshotter.tryWithSnapshot (/home/gmc/Área de Trabalho/crawler-google-places/src/error-snapshotter.js:58:20)
>       at async module.exports.handlePlaceDetail (/home/gmc/Área de Trabalho/crawler-google-places/src/detail_page_handle.js:76:12)
>       at async handlePageFunctionExtended (/home/gmc/Área de Trabalho/crawler-google-places/src/places_crawler.js:77:13)
>       at async ErrorSnapshotter.tryWithSnapshot (/home/gmc/Área de Trabalho/crawler-google-places/src/error-snapshotter.js:58:20)
>       at async PuppeteerCrawler.handlePageFunction [as userProvidedHandler] (/home/gmc/Área de Trabalho/crawler-google-places/src/places_crawler.js:161:13)
>       at async PuppeteerCrawler._handleRequestFunction (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/apify/build/crawlers/puppeteer_crawler.js:316:13)
>       at async PuppeteerCrawler._runTaskFunction (/home/gmc/Área de Trabalho/crawler-google-places/node_modules/apify/build/crawlers/basic_crawler.js:381:13)

This is my input

{
  "searchStringsArray": ["farmacia"],
  "language": "pt-br",
  "maxReviews": 1,
  "maxImages": 1,
  "country": "brasil",
  "state": "sao paulo",
  "city": "osasco",
  "zoom": 15,
  "proxyConfig": {
    "useApifyProxy": false
  }
}

**Comment by metalwarrior665** [comment]
Hello,

This was fixed already a week ago
