### ISSUE TITLE
Try to add an exact date time for reviews

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#117]
It might be buried somewhere in the XHRs

**Comment by metalwarrior665** [comment]
Added it beta, latest tomorrow

**Comment by uridah** [comment]
How can I set an exact date time for reviews within apify?

**Comment by metalwarrior665** [comment]
This is being scraped, the date is there in the data

**Comment by uridah** [comment]
Got it, I got the impression that maybe we can specify date in the input too.
