### ISSUE TITLE
Cookies approval has new layout

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#133]

**Comment by metalwarrior665** [comment]
I adjusted to the new layout but want to keep testing

**Comment by JochenFromm** [comment]
Could it be that the URL of the consent page has changed? The `intro` part in the URL which is specified [here](https://github.com/drobnikj/crawler-google-places/blob/master/src/places_crawler.js#L142) seems to be missing.

**Comment by metalwarrior665** [comment]
Yes, it changed and the layout/button too.
