### ISSUE TITLE
Opening hours are no extracted

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#146]
New change

https://my.apify.com/view/runs/D9yr9Ey323JdgPZju

**Comment by cmatthew11** [comment]
I'm also having the same problem, asking for opening hours but they aren't printed in the output headings

https://my.apify.com/view/runs/xiD7Uuv9XgQepFLez

**Comment by mattiashtd** [comment]
I'm looking into this now.

**Comment by mattiashtd** [comment]
Here's the PR for the fix: https://github.com/drobnikj/crawler-google-places/pull/156
