### ISSUE TITLE
reviewsCount returns 1 for counts over 1,000 reviews

### ISSUE THREAD

**Issue by mcarchon** [drobnikj/crawler-google-places#15]
For any place on Google Maps with over 1,000 reviews the crawler returns 1 for the reviewsCount variable. 

One of the locations showing the issue:
https://www.google.com/maps/place/Ozone+Coffee+Roasters,+Leonard+Street/@51.5246824,-0.0890439,17z/data=!3m1!4b1!4m5!3m4!1s0x48761caf43c8ccb5:0xc637888786396ed2!8m2!3d51.5246824!4d-0.0868552

![image](https://user-images.githubusercontent.com/6044829/67751500-826c7c00-fa31-11e9-82cb-671a549cf575.png)

As you can see, there is a dot as thousand separator which if I'm reading the code correctly is not filtered out, resulting in the match function only matching the first digits before the separator, being 1 in this case.
See https://github.com/drobnikj/crawler-google-places/blob/master/src/places_crawler.js#L143

**Comment by drobnikj** [comment]
@mcarchon Thanks for the bug report. It was fixed.
