### ISSUE TITLE
Option to scrape reviews only up to certain date

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#159]

**Comment by uridah** [comment]
Hello, following up on this.
Is there a way to scrape reviews after a certain date?
If there is no direct way of doing this, can I find/implement any other workarounds?

**Comment by metalwarrior665** [comment]
Hello, we can definitely build this feature but it will take a bit of time as we are prioritizing.

You can always scrape all reviews and then filter it out once you have the data.

**Comment by uridah** [comment]
> Hello, we can definitely build this feature but it will take a bit of time as we are prioritizing.
> 
> You can always scrape all reviews and then filter it out once you have the data.

Basically, I have thousands of locations for which I am scraping and it takes days till the actor completes its run. Running the whole thing again every few days is not feasible in my use case.
I want to setup a cron job to bring in new reviews only on a monthly or weekly basis.

**Comment by metalwarrior665** [comment]
This is now implemented
