### ISSUE TITLE
When Running Apify.Main() TypeError Occurs

### ISSUE THREAD

**Issue by cpusch** [drobnikj/crawler-google-places#160]
When attempting to run program locally get error as seen in screen shot. I am quite new to JS and programming in general so if I did something wrong please let me know. 

![image](https://user-images.githubusercontent.com/42036285/123130289-84066700-d401-11eb-88e0-2b00cc849631.png)

**Comment by pocesar** [comment]
you should be running using `apify run`, refer to the guide here https://sdk.apify.com/docs/guides/apify-platform

**Comment by cpusch** [comment]
I have used apify run but the same error is thrown. Should I be setting some sort of environment variables for it to run locally?

**Comment by pocesar** [comment]
from your screenshot, you used `npm run start`. you also need to use `apify init` and edit your `apify_storage\key_value_stores\default\INPUT.json` file with your input
