### ISSUE TITLE
Making use of this code without apify platform

### ISSUE THREAD

**Issue by BleepLogger** [drobnikj/crawler-google-places#163]
I am a Python and C programmer, I don't really understand JS. So I can't figure out how to use this code without the apify platform.

**Comment by metalwarrior665** [comment]
You can run this locally and you don't need to know JS. Just clone the repo and follow steps here - https://sdk.apify.com/docs/guides/quick-start#local-usage-with-apify-command-line-interface-cli

**Comment by BleepLogger** [comment]
Thank you so much for the fast response! I'm so glad that you directed me
to the steps. If there is anything I can ever do for you, please do tell me.
