### ISSUE TITLE
Opening hours not getting scrapped for certain places

### ISSUE THREAD

**Issue by hectorgm** [drobnikj/crawler-google-places#164]
The opening hours information does not get scraped for places that contain more than one kind of opening hours (e.g.: in-store, drive through, online...) or information about when the business last updated it.

Examples:

- [https://www.google.com/maps/place/Village+d'Ung/@48.870321,2.3107268,19z/data=!3m1!4b1!4m5!3m4!1s0x47e66fc59046af91:0x5591629ab3d68623!8m2!3d48.870321!4d2.311274](url)
- [https://www.google.com/maps/place/Anytime+Fitness+Igualada/@41.5799921,1.6160404,17z/data=!3m1!4b1!4m5!3m4!1s0x12a469041cf1bdf9:0xa1385c3d013d1b3e!8m2!3d41.5799871!4d1.6182281?hl=en](url)
- [https://www.google.com/maps/place/Restaurante+La+Tagliatella+%7C+Manresa/@41.7314496,1.8176481,15z/data=!4m5!3m4!1s0x0:0xfc653ca88dfd7f0c!8m2!3d41.7254609!4d1.8247446](url)
- [https://www.google.com/maps/place/McDonald's/@41.5907075,1.6160677,17z/data=!4m5!3m4!1s0x12a4427544614d0b:0x9a331380ec9f79dd!8m2!3d41.5907035!4d1.6183124](url)

![image](https://user-images.githubusercontent.com/12633036/123983674-594d7d00-d9c4-11eb-9779-fdafff0af93e.png)

![image](https://user-images.githubusercontent.com/12633036/123984975-60c15600-d9c5-11eb-9afd-c90580e935d1.png)

**Comment by metalwarrior665** [comment]
Thanks a lot for detailed report, we will try to fix this soon.

**Comment by metalwarrior665** [comment]
Should be fixed
