### ISSUE TITLE
Performance, Optimization Options

### ISSUE THREAD

**Issue by CamJW101** [drobnikj/crawler-google-places#175]
Hello! Before I begin I just want to say that this is great software! Good job to everyone involved!

Currently, I get about 4 results per minute. While this is awesome, I'd like to speed this up in any way possible to get results more quickly. 

What features/optimizations are there to increase the speed of scans? I've looked into Apify's documentation on this, but haven't found anything substantive yet. What are the performance options available and how do I change them?

Thanks for your help! If you'd like any more information about my setup, I'd be happy to give it.

**Comment by metalwarrior665** [comment]
Hello,

There isn't any secret performance mode to be uncovered as we try to make the scraper reasonable fast for everyone :) It is using a browser which means it will always be slower than direct API calls.

To speed things up, make sure you disable all the extra data options in Output Configuration section of the input. The only other option is to simply add more memory (which adds more CPU) to the run which makes it proportionally faster.

**Comment by CamJW101** [comment]
Thanks for the response! Thanks for the great software!
