### ISSUE TITLE
How to use apify with multiple inputs?

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#186]
Dear all, Finally am able to run apify on my local PC
Now let's say am working on a server and I want my users t use my server to search for their favorite places.
As I can see, apify run one session at the same time.

What is the correct method to call apify in the background when I have a new input file?
and how can I "identify" each out put to their inputs.

Is there a way to run apify in the background as a web server and pass the input file path along with the output path?
so in this case I have one processes in the background as server.

Thank you for your help,

**Comment by metalwarrior665** [comment]
Hello,

If you want to run this on your server, you have to figure out the system yourself. Apify is a normal Node.js program so the same things apply here.

**Comment by beshoo** [comment]
@metalwarrior665 

Thank you so much for the kind reply.
Well, It will be great if you can share with me some hints if you know the how-to since am new to the nodeJs
Kind of where to start. reading all files will take time to understand how things work.

Am sure this is already done before, so why to recreate the wheel.
Saving time will be great.

Thank you so much.

**Comment by metalwarrior665** [comment]
Actually, most of the users here run it on the Apify platform which simplifies everything. You can create a free account there. Users that run this on their server have each really custom setup.
