### ISSUE TITLE
Error when extracting reviews - Waiting for back navigation on reviews page ran into a timeout after 10s on URL

### ISSUE THREAD

**Issue by cloudlucky** [drobnikj/crawler-google-places#206]
When I run the tasks to get the reviews, sometimes I get this error message:
Error: Operation failed: Reviews extraction. Error detail: Waiting for back navigation on reviews page ran into a timeout after 10s on URL: <a URL>

It seems to be always at the end when all the reviews has been extracted but then it fails and retries

Here is the log: 
[Zy6FyEdxFEl0YlzLn.log](https://github.com/drobnikj/crawler-google-places/files/7428573/Zy6FyEdxFEl0YlzLn.log)

And an Input that I'm using: 
[INPUT.json.txt](https://github.com/drobnikj/crawler-google-places/files/7428584/INPUT.json.txt)

I have 178 tasks configured to run every day and the last time that I ran all of them, it happened for 27 tasks.
On October 26th, it happened 13 times and the day before, 8 times.

Error state:
- [ERROR-SNAPSHOT-Reviews-extraction-Waiting-for-back-navigation-on-reviews-page-ran-into-a-timeou](https://user-images.githubusercontent.com/518200/139129056-9f37b378-57d0-4293-865d-1c23e3aab585.jpg)
- [ERROR-SNAPSHOT-Reviews-extraction-Waiting-for-back-navigation-on-reviews-page-ran-into-a-timeou.html.txt](https://github.com/drobnikj/crawler-google-places/files/7428619/ERROR-SNAPSHOT-Reviews-extraction-Waiting-for-back-navigation-on-reviews-page-ran-into-a-timeou.html.txt)
- [ERROR-SNAPSHOTTER-STATE.json.txt](https://github.com/drobnikj/crawler-google-places/files/7428620/ERROR-SNAPSHOTTER-STATE.json.txt)

**Comment by metalwarrior665** [comment]
@cloudlucky I merged the fix into the repo - https://github.com/drobnikj/crawler-google-places/pull/207

We will be testing it a bit in the `beta` build. I would be happy if you could also test it in `beta` build but we will probably release it into `latest` tomorrow.

**Comment by cloudlucky** [comment]
@metalwarrior665 this is a good news :)

I tested some URLs and I didn't get the issue. But at the same time, it was not happening all the time, only time to time and not only on the same URL.

Anyway, I some tests with the beta version and everything seems good.

Thank you

**Comment by metalwarrior665** [comment]
Forgot to close after fix
