### ISSUE TITLE
[QUESTION] How to force english language?

### ISSUE THREAD

**Issue by joelbqz** [drobnikj/crawler-google-places#21]
Hello guys, when the scrapper uses proxies based on countries which english is not their primary language, location details and reviews get all in other languages. I came with a hacky solution to this:

file: `/src/main.js`

This didn't worked:
![image](https://user-images.githubusercontent.com/19965325/70474777-32a5b980-1aa1-11ea-9ac3-849bb406ebc3.png)

Also tried this to force URL ?hl=en but didn't work 
![image](https://user-images.githubusercontent.com/19965325/70474854-50731e80-1aa1-11ea-83a0-b62e948edf98.png)

After testing locally I watching Chromium running the crawler I noticed at some point when the function extractPlaceDetail() starts running, it suddenly closes and re-opens the current browser tab, then when this happens the new tab doesn't have the hl?=en(I never found what part of the code does this action), so when the new tab opens, what I did was to force it to refresh to the url with ?hl=en param appended again.

file: `/src/places_crawler.js`

![image](https://user-images.githubusercontent.com/19965325/70475354-5a495180-1aa2-11ea-8d4d-c4886db96e7c.png)

This solves the issue but I think it is kinda hacky, I just wanted to share what I did, hope this helps.

**Comment by joelbqz** [comment]
Update: now the crawler is more expensive to run on Apify(I assume it is because of `await.goto(page.url()+'?hl=en')`) is there a way to avoid this reload?

**Comment by drobnikj** [comment]
Hey @joelbqz,

I don't know a solution about how to force google maps scraper to use English. The only way which I'm using is a proxy from the US, which works well for me, but you need to find a good proxy provider.
I will look into your solution later, maybe there is a way.

If you are using Apify proxy I can give you a few US proxies to test. If you are interested, please contact Apify support.

**Comment by metalwarrior665** [comment]
This option has been added to input now.
