### ISSUE TITLE
Enable searching all places in a location without search

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#220]
Currently, you have to provide either search or start URLs and there is not a default way to scrape through all possible categories. We would probably have to mock all major categories, I don't think there is really a way to ensure getting all places but it could get close.

More here:
https://www.reddit.com/r/webscraping/comments/rafda5/scraping_an_entire_town_with_google_maps_api/

**Comment by metalwarrior665** [comment]
This is now implemented!

**Comment by zhiyue** [comment]
@metalwarrior665  Maybe use the categories on this url: https://developers.google.com/maps/documentation/places/web-service/supported_types#table1

**Comment by metalwarrior665** [comment]
@zhiyue That's an option but then you need to scrape all these separately which would be huge. For now we take all pins from the map.
