### ISSUE TITLE
How to start crawling in Docker

### ISSUE THREAD

**Issue by flaiming** [drobnikj/crawler-google-places#225]
I would like to use this crawler on my server, so I tried to use it as docker with default Dockerfile. But I am having trouble to find any way how to start the crawling. What I did:

* build docker with `docker build .`
* run docker with `docker run -it <imageID> bash`
* attempt to start crawling on sample inputs by `npm start inputs/SEARCH.json` (inputs files are not accesible to user, so i copied it to home, but the content is the same) or `APIFY_LOCAL_STORAGE_DIR=test INPUT=search_test.json npm start`

What I got in both tries was `TypeError: Cannot read property 'searchStringsArray' of null` because input is `null`. Looks like I'm not giving input the right way. 

My question is - what is the right way how to run this crawling in docker? Do I need Apify account for that? And is there documentation for that/will there be one?

**Comment by metalwarrior665** [comment]
Hello, You don't need Apify account unless you run on Apify platform or use Apify proxies. So you are not passing in the input correctly. I don't have much experience with Docker but you will have to smuggle it into the disk of the container. By default it is looking into `./apify_storage/key_value_stores/default/INPUT.json`

Second options is: Nothing prevents you from updating the code and passing in the input any way you want, it is just a JSON object it gets from some place (disk/API call/whatever you wish)

**Comment by flaiming** [comment]
@metalwarrior665 Thanks for answer, but in the end I just wrote my own google maps crawler, it was not so hard after all :)
