### ISSUE TITLE
How to parse JSON ?

### ISSUE THREAD

**Issue by CMingTseng** [drobnikj/crawler-google-places#226]
Dear sir

I have the same idea !!

i try  get 

https://www.google.com/maps/preview/place?authuser=0&hl=XXX&gl=XX&pb=XXXXXX&q=餐廳&pf=t

to  get near places information 

but  when i get  JSON    can not covert to  object class ( java /kotlin/  dart )

can give me  something ?  about parse JSON 

THX

**Comment by metalwarrior665** [comment]
You can check the code how we do it
