### ISSUE TITLE
Crawling entire country with high zoom failed

### ISSUE THREAD

**Issue by lz000** [drobnikj/crawler-google-places#231]
I'm trying to crawl all restaurants in US as much as possible. So I specified country `USA` and zoom `18` , no state , city etc. I'm on free trial. Here is the full input

```
{ "searchStringsArray": [ "restaurant" ], "maxCrawledPlacesPerSearch": 9999999, "maxCrawledPlaces": 9999999, "zoom": 18, "language": "en", "exportPlaceUrls": false, "includeHistogram": false, "includeOpeningHours": true, "includePeopleAlsoSearch": false, "additionalInfo": true, "maxImages": 0, "maxReviews": 0, "scrapeReviewerName": true, "scrapeReviewerId": true, "scrapeReviewerUrl": true, "scrapeReviewId": true, "scrapeReviewUrl": true, "scrapeResponseFromOwnerText": true, "proxyConfig": { "useApifyProxy": true }, "country": "USA", "reviewsSort": "newest", "reviewsTranslation": "originalAndTranslated", "maxConcurrency": 100, "maxPageRetries": 6, "pageLoadTimeoutSec": 60, "maxPagesPerBrowser": 1 }
```

I stated a run. From the log I saw it stuck at the `Location found` for around 30min then was killed. There was a message showing on the top saying it was out of memory.

Here is the full log 
```
2022-01-19T04:24:12.612Z ACTOR: Pulling Docker image from repository. 
2022-01-19T04:24:12.686Z ACTOR: Creating Docker container. 
2022-01-19T04:24:12.823Z ACTOR: Starting Docker container. 
2022-01-19T04:24:14.841Z INFO System info {"apifyVersion":"1.3.4","apifyClientVersion":"1.4.2","osType":"Linux","nodeVersion":"v14.18.2"} 
2022-01-19T04:24:15.250Z INFO Using zoom 18 to define the search 
2022-01-19T04:24:18.224Z INFO [Geolocation]: Location found: United States, lat: 39.7837304, long: -100.445882 
2022-01-19T05:01:23.702Z Killed 
2022-01-19T05:01:23.814Z
```

Here is the stats. The memory was around 1.3g
```
Compute units

2.4795

Memory

Average:1.3 GB

Maximum:4.1 GB

CPU

Average:94.66%

Maximum:121.63%
```

I'm wondering if increasing memory will make it work? or specifying only the country USA with zoom 18 will never work?

**Comment by zpelechova** [comment]
Hey, I don't think increasing memory will do much. Generally with the whole country we recommend zoom 12 respectively the actor is set to choose this zoom when you only input country. But it will still take a lot of time. Give it a try like this or try for a state first?

**Comment by metalwarrior665** [comment]
You run out of memory. Increasing it might solve it but zoom 18 with USA would never end. For US scrape I highly recommend splitting into major cities or at least densely populated states (north east), otherwise it spends a lot of time in deserts and empty locations. We plan to do this automatically for sparsely populated countries but not implemented yet.
