### ISSUE TITLE
Type "Polygon" and "coordinates" not working properly

### ISSUE THREAD

**Issue by pcholewa** [drobnikj/crawler-google-places#237]
Hi,

I have input file like below. The downloaded places are not in "coordinates" from input file. Am I doing something wrong?

{
    "searchStringsArray": [
        "Warsztat samochodowy"
    ],
    "maxCrawledPlaces": 9999999,
    "language": "pl",
    "maxReviews": 0,
    "includeImages": true,
    "maxImages": 50,
    "includeHistogram": false,
    "includeOpeningHours": true,
    "includePeopleAlsoSearch": false,
    "additionalInfo": false,
    "reviewsSort": "mostRelevant",
    "reviewsTranslation": "originalAndTranslated",
    "exportPlaceUrls": false,
    "zoom": 16,
    "maxAutomaticZoomOut": 1,
    "proxyConfig": {
        "useApifyProxy": false
    },
    "maxConcurrency": 100,
    "maxPageRetries": 100,
    "pageLoadTimeoutSec": 60,
    "maxPagesPerBrowser": 1,
    "useChrome": false,
    "debug": false,
    "useStealth": false,
    "scrapeReviewerName": false,
    "scrapeReviewerId": false,
    "scrapeReviewerUrl": false,
    "scrapeReviewId": false,
    "scrapeReviewUrl": false,
    "scrapeResponseFromOwnerText": false,
    "type": "Polygon",
    "coordinates": [
        [
            [52.36347847861958, 21.277367031359567],
            [52.3575853478122, 21.214612065457352],
            [52.33292945833162, 21.2156438202159],
            [52.33500627398268, 21.280037455440514],
            [52.36347847861958, 21.277367031359567]
        ]
    ]
}

**Comment by HALAMHA** [comment]
Hi there, 
longitude needs to go first, so it should look like this:
[
[ 21.277367031359567, 52.36347847861958],
[21.214612065457352, 52.3575853478122],
[21.2156438202159, 52.33292945833162],
[21.280037455440514, 52.33500627398268],
[21.277367031359567, 52.36347847861958]
]

Works well for me with this polygon, please test it and let me know how it went :)

**Comment by pcholewa** [comment]
still not working properly. Below is all my INPUT.json content. I got places from other coordinates. Can You send all Your working INPUT.json example?

{
    "searchStringsArray": [
        "Warsztat samochodowy"
    ],
    "maxCrawledPlaces": 9999999,
    "language": "pl",
    "maxReviews": 0,
    "includeImages": true,
    "maxImages": 50,
    "includeHistogram": false,
    "includeOpeningHours": true,
    "includePeopleAlsoSearch": false,
    "additionalInfo": false,
    "reviewsSort": "mostRelevant",
    "reviewsTranslation": "originalAndTranslated",
    "exportPlaceUrls": false,
    "zoom": 16,
    "maxAutomaticZoomOut": 1,
    "proxyConfig": {
        "useApifyProxy": false
    },
    "maxConcurrency": 100,
    "maxPageRetries": 100,
    "pageLoadTimeoutSec": 60,
    "maxPagesPerBrowser": 1,
    "useChrome": false,
    "debug": false,
    "useStealth": false,
    "scrapeReviewerName": false,
    "scrapeReviewerId": false,
    "scrapeReviewerUrl": false,
    "scrapeReviewId": false,
    "scrapeReviewUrl": false,
    "scrapeResponseFromOwnerText": false,
    "type": "Polygon",
    "coordinates": [
        [
            [20.4077, 53.76617],
            [20.49319, 53.81849],
            [20.59104, 53.77571],
            [20.50212, 53.72627],
            [20.4077, 53.76617]
        ]
    ]
}

**Comment by HALAMHA** [comment]
You need to use proxy (automatic)

**Comment by pcholewa** [comment]
what do You mean? Can You put here an example?

**Comment by HALAMHA** [comment]
"proxyConfig": {
    "useApifyProxy": true
  },
  
If you don't have access to proxy, please contact support.
