### ISSUE TITLE
How to use on local machine? 

### ISSUE THREAD

**Issue by oadailton** [drobnikj/crawler-google-places#238]
Hello, I already downloaded the file on my computer, I ran some files from the “src” folder with Node, and it didn't work.
Does anyone have a way to run it from Node JS?

**Comment by pocesar** [comment]
you can run on Node, you'll need to follow the instructions here https://sdk.apify.com/docs/guides/motivation
TL;DR: you need to use `apify run --purge` instead of running files

**Comment by deweydb** [comment]
As this took me a bit of time to figure out here's the full steps

```git clone https://github.com/drobnikj/crawler-google-places.git
cd crawler-google-places
npm install apify
apify run --purge
# now add the INPUT.json file to apify_storage/key_value_stores/default
apify run --purge```

**Comment by danielehrhardt** [comment]
Will this use the apify Servers or the Local machine?
