### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'maxCrawledPlaces')

### ISSUE THREAD

**Issue by oadailton** [drobnikj/crawler-google-places#239]
After clarifying my previous question, I started to understand better how the system works, but now when I type apify run --purge

This error appears:

ERROR
  TypeError: Cannot read properties of null (reading 'maxCrawledPlaces')
      at module.exports.makeInputBackwardsCompatible (C:\Users\Usuario\Downloads\crawler-google-places-master\crawler-google-places-master\src\input-validation.js:17:15)
      at C:\Users\Usuario\Downloads\crawler-google-places-master\crawler-google-places-master\src\main.js:25:5
      at async run (C:\Users\Usuario\Downloads\crawler-google-places-master\crawler-google-places-master\node_modules\apify\build\actor.js:182:13)
Error: npm.cmd exited with code 91

In the inputs/search.json file it looks like this:

{
    "searchStringsArrays": [
      "restaurant"
    ],
    "maxCrawledPlaces": 999999,
    "language": "en",
    "maxReviews": 5,
    "maxImages": 2,
    "includeHistogram": true,
    "includeOpeningHours": true,
    "includePeopleAlsoSearch": true,
    "additionalInfo": true,
    "reviewsSort": "mostRelevant",
    "reviewsTranslation": "originalAndTranslated",
    "exportPlaceUrls": false,
    "county": "orange",
    "zoom": 12,
    "proxyConfig": {
      "useApifyProxy": true
    },
    "maxConcurrency": 100,
    "maxPageRetries": 6,
    "pageLoadTimeoutSec": 60,
    "maxPagesPerBrowser": 1,
    "useChrome": false,
    "debug": false,
    "useStealth": false,
    "scrapeReviewerName": true,
    "scrapeReviewerId": true,
    "scrapeReviewerUrl": true,
    "scrapeReviewId": true,
    "scrapeReviewUrl": true,
    "scrapeResponseFromOwnerText": true
  }

What could possibly be happening? I did all the same procedure as indicated on the site correctly.

**Comment by metalwarrior665** [comment]
You need to pass in the input via `apify_storage/key_value_stores/default/INPUT.json`
