### ISSUE TITLE
Is there any way to export the contents in XML by Apify-CLI?

### ISSUE THREAD

**Issue by oadailton** [drobnikj/crawler-google-places#240]
After two doubts I managed to get the code to run, and I already got results.
To finish, after having done all the procedures, it worked and saved all the places perfectly each file separately in .json, I would like to know if by Apify itself I can unite them and export them in XML, or if I can only do it manually or through other codes?
I studied the SDK manual, but it was not very enlightening.

**Comment by pocesar** [comment]
the XML transform is offered by https://apify.com platform, and the dataset that the Apify SDK generates locally is JSON-only. 
you'll need to create your own solution for transforming them into XML files. a quick search on google showed me this (I didn't try): https://www.npmjs.com/package/xml-js

**Comment by oadailton** [comment]
I created a nice code that is working, could I be adding it with your files to help the next users?
