### ISSUE TITLE
Only one array of "searchStringsArray" its searched

### ISSUE THREAD

**Issue by oadailton** [drobnikj/crawler-google-places#243]
I managed to scrape the first results, and they were a success. However, then I went to put more strings in the "searchStringsArray" field, but it only brought a single result, the other strings was ignored, look at my configuration:

`{
   "searchStringsArray":[
      "restaurante lagoinha",
      "pousada lagoinha",
      "hotel lagoinha",
      "bar lagoinha",
      "padaria lagoinha",
      "mercado lagoinha",
      "supermercado lagoinha",
      "rodoviaria lagoinha"
   ],
   "maxCrawledPlaces": 99999999,
   "language":"en",
   "exportPlaceUrls":false,
   "includeHistogram":true,
   "includeOpeningHours":true,
   "includePeopleAlsoSearch":false,
   "additionalInfo":true,
   "reviewsSort":"newest",
   "reviewsTranslation":"originalAndTranslated",
   "scrapeReviewerName":false,
   "scrapeReviewerId":false,
   "scrapeReviewerUrl":false,
   "scrapeReviewId":false,
   "scrapeReviewUrl":false,
   "scrapeResponseFromOwnerText":true,
   "proxyConfig":{
      "useApifyProxy":false
   },
   "maxConcurrency":1,
   "maxPageRetries":99999999,
   "pageLoadTimeoutSec":99999999,
   "maxPagesPerBrowser":1,
   "maxImages":4
}`

Of these strings only "pousada lagoinha" was scraped

**Comment by metalwarrior665** [comment]
Hello,

These huge values cause a corrupted behavior
```
"maxPageRetries":99999999, "pageLoadTimeoutSec":99999999
```
Please reduce them to reasonable values
```
"maxPageRetries":3, "pageLoadTimeoutSec":120
```

Other than that, I tested it and all works fine
