### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by mattiashtd** [drobnikj/crawler-google-places#275]
Google Maps has removed the pagination buttons.
For this reason only the first results per search are found and the logs show error messages (even if we limit "maxCrawledPlacesPerSearch": 1).

**Steps to reproduce:**
Start the crawler e.g. with this configuration:

```
{
  "startUrls": [
    "https://www.google.com/maps/search/restaurants+in+Berlin,+Germany/"
  ],
  "maxCrawledPlaces": 99999999,
  "proxyConfig": {
    "proxyUrls": [
      "TODO:ADD PROXY URL"
    ]
  }
}
```

**Result:** 
20 places are extracted and an error like this is displayed in the logs:

```
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/search/restaurants+in+Berlin,+Germany/?hl=en","retryCount":1,"id":"..."}
  Error: Operation failed. Error detail: [SEARCH][null][PAGE: 1]: Don't recognize the loaded content - https://www.google.com/maps/search/restaurants+in+Berlin,+Germany/?hl=en
      at module.exports.enqueueAllPlaceDetails (/Users/mattiashilliges/git/crawler-google-places_fork/src/enqueue_places.js:347:19)
      at async ErrorSnapshotter.tryWithSnapshot (/Users/mattiashilliges/git/crawler-google-places_fork/src/error-snapshotter.js:59:20)
      at async handlePageFunctionExtended (/Users/mattiashilliges/git/crawler-google-places_fork/src/places_crawler.js:55:13)
      at async ErrorSnapshotter.tryWithSnapshot (/Users/mattiashilliges/git/crawler-google-places_fork/src/error-snapshotter.js:59:20)
      at async PuppeteerCrawler.handlePageFunction (/Users/mattiashilliges/git/crawler-google-places_fork/src/places_crawler.js:168:13)
      at async wrap (/Users/mattiashilliges/git/crawler-google-places_fork/node_modules/@apify/timeout/index.js:73:27) 
```

**Expected result:**
All places which belong to the startUrl are extracted.

**Comment by mattiashtd** [comment]
I will try to fix it using scrolling.

**Comment by metalwarrior665** [comment]
I actually intended to work on this tomorrow but maybe we can race who is faster :) This will be a bigger change

**Comment by mattiashtd** [comment]
@metalwarrior665 Cool, then I will leave it to you. I didn't actually write any code until now.
But my idea was to loop like this, until no more articles are found or the end text is reached:
```
let articles = document.querySelectorAll("[role=article]")
articles[articles.length-1].scrollIntoView()
.. wait for the loading animation to go away ..
```

Additionally I saw that sometimes the loading animation doesn't go away, so this probably also needs extra handling.

**Comment by mattiashtd** [comment]
Cool, probably my solution would have taken longer to implement :)
I also guess the loader problem happens if we scroll too fast.
Thank you for the update!

**Comment by mattiashtd** [comment]
Many thanks for the quick fix! @metalwarrior665 

I tested it locally and seems to work pretty well.
It looks like the limit of 120 places per search is not always true. When I search for "Restaurants in Berlin", I get 122 results - but this seems to be a special search, I could verify the limit of 120 for other searches :)

I checked those 122 by executing in the Chrome console:
```
function sleep(milliseconds) {
 return new Promise(resolve => setTimeout(resolve, milliseconds));
}

async function scroll() {
  let articles = document.querySelectorAll("[role=article]")
  articles[articles.length-1].scrollIntoView()
  await sleep(4000);
  console.log(articles);
  console.log(articles.length);
  await scroll();
}

scroll();
```

Another small thing: It looks like crawling pages with only a few results takes quite long now (e.g. when searching _Burger in Beeskow_)
Maybe this could be somehow improved by waiting for the element which marks the end of the list.

But those are only small details :)
Overall it seems to work pretty well already.

**Comment by mattiashtd** [comment]
@metalwarrior665 Thank you for the info about 1. Probably those 2 are ads then :)
2. My idea was to use the end marker in the HTML, i.e. the element which has text "You've reached the end of the list." (class "HlvSq"). But I didn't try if this would actually work. Thank you again for the quick hotfix!

**Comment by metalwarrior665** [comment]
Ah good catch, I missed this somehow. Will add it asap.
