### ISSUE TITLE
Request version for running on own machine

### ISSUE THREAD

**Issue by buiducnhat** [drobnikj/crawler-google-places#276]
Many thank to authors who wrote this application. I am using it at Apify now but I feel it run slowly. So can you make a version for scraping on user's own machine? Thank you so much!

**Comment by metalwarrior665** [comment]
What exactly is the source of slowness? Apify in infinitely scalable, you can apply more memory to the run and split the start URLs into more actor runs so you can scrape as fast as needed.

**Comment by metalwarrior665** [comment]
Put the country and then the name of the category into the search array.

**Comment by danielehrhardt** [comment]
Is it possible to run this on the local Environment?

**Comment by metalwarrior665** [comment]
Yes, it is a Node.js program
