### ISSUE TITLE
Crawler statistic

### ISSUE THREAD

**Issue by Keeyahto** [drobnikj/crawler-google-places#278]
Hi! I'm not too good at js, so could you explain to me how to understand this line in the parser logs?
`INFO  [STATS]: failed: 0 | ok: 16516 | outOfPolygon: 295218 | outOfPolygonCached: 295218 | places: 799 | maps: 15717`
I understand what the failed and places values mean, but the rest is not clear to me. Could you help me with this?

**Comment by metalwarrior665** [comment]
I agree this log should be improved, thanks for the feedback.

`outOfPolygon` are places that were found in the search but were not located in the exact boundaries of searched area. Seems you had a lot of them. What is your input? 
`outOfPolygonCached` is basically the same
`places`: is how many place detail pages we visited
`maps` how many map search pages we visited

**Comment by Keeyahto** [comment]
Thanks for the reply. I'm parsing information about some companies in Norway. I also have a question. Since I don't need photos, can I increase the performance of the parser by enabling the flag '--blink-settings=imagesEnabled=false'?

**Comment by metalwarrior665** [comment]
This is already done in the code. The map is need in the search phase.

**Comment by Keeyahto** [comment]
Thanks for the help
