### ISSUE TITLE
Supporting Mysql

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#279]
Dear all,

How can we save the output into MySQL ?

Regards

**Comment by metalwarrior665** [comment]
If you run on Apify platform, you can use of the actor in the Store to send dataset data to MySQL. Locally, you will have to transform the JSON results yourself

**Comment by beshoo** [comment]
Thank you for the reply, I mean what if I want to alter the javascript and add the insert SQL statement. is there any storage class I can update?

regards

**Comment by metalwarrior665** [comment]
The storage class in the Apify SDK, but you don't need to touch that. Just change the Apify.pushData function

**Comment by beshoo** [comment]
Dear @metalwarrior665 
Thank you so much for your reply

I found it kind of complicated to make the Mysql table for the json since it has a lot of subnodes like reviews and other things which are represented in the JSON.

So I search if APIFY has something for MySQL, and I found this 
https://github.com/cermak-petr/act-mysql-insert

Is it possible to use act-mysql-insert ?
Kindly may you advise me on how to use this tool to create a table and insert it by using the **act-mysql-insert**

Thank you and best regards

**Comment by metalwarrior665** [comment]
You can use it but you need to run it on Apify platform, not local dataset
