### ISSUE TITLE
Just wanted the Google Place urls not details

### ISSUE THREAD

**Issue by chiragjak** [drobnikj/crawler-google-places#29]
Hello I am your current customer, for Google Place scraper i just wanted to collect the google place URLs not details for the google places, So is that something you can provide me or help me, please?

In scraper there is no option to do that currently. if it is possible can you do that please?

**Comment by metalwarrior665** [comment]
I agree that we should add this option.

**Comment by metalwarrior665** [comment]
This has been added.
