### ISSUE TITLE
Located In field is wrongly merged into address

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#32]
Small formatting error

**Comment by AndreyBykov** [comment]
How it should look like? In last build, for new selector output looks like this now:
`"address": "Pobřežní 1, 186 00 Praha 8-Karlín, Czechia Located in: Hilton Prague"`

**Comment by metalwarrior665** [comment]
This looks better than before (was without any whitespace). But I would still prefer a separate field.

**Comment by metalwarrior665** [comment]
Fixed.
