### ISSUE TITLE
Parse address into street, city, state, zip and country

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#34]
Let's leave the `address` field as it is now for backward compatibility

**Comment by mercuryyy** [comment]
can prase into
address_full
address
state
city
zip

I think this is great, most places will import by address,state,city,zip all crm's all other related data imports. 

Will be very helpfull !

**Comment by metalwarrior665** [comment]
Implemented in `beta`, will be fully released in upcoming days
