### ISSUE TITLE
Open Hours not accessible

### ISSUE THREAD

**Issue by Astriel** [drobnikj/crawler-google-places#39]
Hello there ! 

Just wanted to check something. I'm actually using the crawler on Apify. Here is the JSON request sent for each tasks : 

```json
{
  "searchString": "jardin à proximité de Lille",
  "proxyConfig": {
    "useApifyProxy": true
  },
  "includeReviews": false,
  "includeImages": false,
  "includeHistogram": true,
  "includeOpeningHours": true,
  "includePeopleAlsoSearch": false,
  "lat": "50.6361657",
  "lng": "3.0443644",
  "zoom": 10,
  "debug": false
}
```

Like you see, it's supposed to include opening hours. Unfortunatly, whatever I'm searching (even for open shops) this is never returned in the json response data. 

Anything I'm missing ?

**Comment by metalwarrior665** [comment]
Hello,

Sorry for the late reply. Can you send us also your input? There is an option to extract the opening hours.

**Comment by metalwarrior665** [comment]
This should be fixed.
