### ISSUE TITLE
Sort reviews by newest

### ISSUE THREAD

**Issue by NickBrooks** [drobnikj/crawler-google-places#53]
At the moment, reviews come through in random Google decided order, but there is an option to filter the reviews by newest.

![mcds (Custom)](https://user-images.githubusercontent.com/4286755/87870474-95701380-c9e7-11ea-9216-6f91c02c66a6.png)

This would allow scraping weekly without having to fetch all reviews, ie week 1 we fetch `300` reviews, week 2 we see there's now `325` reviews so we only fetch `25`. Or even better, to save a call to Google API to check review count, we could input `300` and it would know to only get the latest `25` once it knows there are 325 reviews. 

Semi relates to: https://github.com/drobnikj/crawler-google-places/issues/20

**Comment by pocesar** [comment]
hey @NickBrooks thanks for your suggestion, it does make sense.
@zzbazza doesn't seem like a major change, change INPUT schema to allow ordering of reviews, one more step for ordering them before parsing

**Comment by metalwarrior665** [comment]
We have added the sorting option, let me know if there would be any problem.

**Comment by metalwarrior665** [comment]
The sorting was a bit buggy until today when should be finally fixed
