### ISSUE TITLE
New review sorting breaks the parser for non-english operations

### ISSUE THREAD

**Issue by xTRiM** [drobnikj/crawler-google-places#56]
Last merge broke the parser for non-english operations. Because google has different layouts for different languages and last merge added code only for english layout.

There seems to be other sorting code just below - maybe we should just make it work? 
It actually kinda works already - it sorts by newest (by keyboard arrow-down operation), and for both "en" and other languages too (as there's 2 Promises for different layouts)

_Originally posted by @xTRiM in https://github.com/drobnikj/crawler-google-places/pull/55#discussion_r459533337_

**Comment by metalwarrior665** [comment]
Thanks a lot. @zzbazza Can you look at it please?

**Comment by zzbazza** [comment]
I will check it.

**Comment by metalwarrior665** [comment]
This should work now, let me know guys if you have any problems.
