### ISSUE TITLE
Broad location search results limit

### ISSUE THREAD

**Issue by j3vr0n** [drobnikj/crawler-google-places#59]
Hi,

We were wanting to do a broad search, for example "Schools in Chicago, Illinois" in order to return all locations that match this criteria. When doing a manual search, we noticed that Google's front-end limits you to 25 pages of results, or 500 locations. Does this limitation also exist in this crawler or can you only do narrow searches for specific locations that you already have indexed?

Thanks!

**Comment by metalwarrior665** [comment]
Hello,

If you fill-up the specific location params - `country`, `state`, `city`, the scraper will split ut the search into many smaller seaches to cover the whole area. This way it should overcome this limit. You will need to play a bit with the `zoom` param to find the ideal granularity for you.
