### ISSUE TITLE
Increase resolution of image URLs

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#62]

**Comment by metalwarrior665** [comment]
Can be done by updating the `w` `h` or `s` "params" in the URLs

**Comment by vorasudh** [comment]
@metalwarrior665 Which URL are you referring to - search URL or URLs of images?

**Comment by metalwarrior665** [comment]
URLs of images. Some users wanted to get the biggest image links by default.

**Comment by metalwarrior665** [comment]
This is done
