### ISSUE TITLE
Using it locally 

### ISSUE THREAD

**Issue by jasonpraful** [drobnikj/crawler-google-places#63]
Apify has limits and restrictions which make using this crawler a bit pricey. Is there any way I can run this crawler locally on my machine? If yes is there any guide I could possibly follow. Thanks in advance.

**Comment by metalwarrior665** [comment]
Hello,

The way to run it locally is the same for all our actors. Have Node.js installed, clone this repo, install `npm i apify-cli -g`, then use `apify init` and `npm install` and you are good to go.

**Comment by jasonpraful** [comment]
Hi, thanks for the swift reply. However, I have run into an issue now where it says " TypeError: Cannot read property 'proxyUrls' of undefined" 

I have configured my INPUT.json appropriately.

If possible could you please post a snippet of your input.json?

Thanks
