### ISSUE TITLE
Google terms modal blocking search results

### ISSUE THREAD

**Issue by denizkoele** [drobnikj/crawler-google-places#73]
Hello,

the google terms cookie modal is blocking the crawler, and prevent grabbing the data.

https://prnt.sc/uy25d6

**Comment by metalwarrior665** [comment]
Hello,

Thanks for bringing this up. The same thing happened in Google Search as well. Does it happen when you run it locally or on Apify platform? Do you use proxies? I would assume it happens only for some IPs (as with Google Search).

**Comment by denizkoele** [comment]
This happens locally. But I guess this is due to the fresh browser.

**Comment by butter2939** [comment]
This happens locally. But I guess this is due to the fresh browser.

The solution could be to ensure that the terms are accepted before scraping the data

**Comment by metalwarrior665** [comment]
Thanks. Maybe there is a cookie that we can pass from the start. That would be ideal. At worst, we will have to click on that.
