### ISSUE TITLE
Cannot force puppeteer to launch with specified options

### ISSUE THREAD

**Issue by sansebi** [drobnikj/crawler-google-places#77]
I noticed while adding `launchPuppeteerOptions `that they will be ignored.
I tried to force a different locale.
`args: ['--lang=de-DE']`

https://github.com/drobnikj/crawler-google-places/blob/c9798198480c43ea618a7ad12ea98678b1acab04/src/main.js#L138

Mostly I get results based on the country of my current proxy IP and sometimes this happens: https://postimg.cc/XGjRPkVP
Is this an anomaly from your library or just puppeteer?
Does someone else experience the same issue?

Forcing the language by an URL parameter doesn't work always and currently only English language is supported.

**Comment by metalwarrior665** [comment]
Thanks for adding this. There is a PR draft to enable all countries. But of course, the URL param is probably not bulletproof. We will continue working on this.

```I noticed while adding launchPuppeteerOptions that they will be ignored.```
You are updating the code or what are you adding?

**Comment by sansebi** [comment]
> You are updating the code or what are you adding?

Yes, I added some code to debug forcing the language.
I am running the code locally based on your comment: https://github.com/drobnikj/crawler-google-places/issues/36#issuecomment-635461859

**Comment by metalwarrior665** [comment]
Oh, I get it, you passed this `args: ['--lang=de-DE']` to the code. Yeah, I think Google will most likely ignore this and use your IP anyway.

**Comment by metalwarrior665** [comment]
If you use the Apify proxy, it can sometimes use a foreign country IP. In Readme, there is a small explanation of how to use US only proxy but I'm not 100% sure it works now.

**Comment by sansebi** [comment]
The point is that I am using 100% private proxies located in Germany and I am still getting a result in cyrillic: https://postimg.cc/XGjRPkVP
Don't think that Google is here the problem.

Could a content language check help out to rerun a new browser instance?

BTW: can you link this issue to your mentioned open PR 👍 

The log shows how puppeteer is launched. It seams so that even your options are ignored

> INFO  Launching Puppeteer {"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"],"timeout":15000,"headless":false,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"################"}

https://github.com/drobnikj/crawler-google-places/blob/c9798198480c43ea618a7ad12ea98678b1acab04/src/main.js#L139

**Comment by pocesar** [comment]
@sansebi thanks for the report, it's both a bug and an enhancement
