### ISSUE TITLE
totalScore is not correctly scraped locally

### ISSUE THREAD

**Issue by HazelCuate** [drobnikj/crawler-google-places#86]
Hi,

The totalScore field is always null or empty string in the output even when the google place actually has a score. For example: https://goo.gl/maps/CbhFcvy2uPM8b6Vu8
```
{
  "title": "A&G Lawyers",
  "subTitle": null,
  "totalScore": null,
  "categoryName": "Lawyer",
  "address": "Calle Ramon Gallud, 78, 03181 Torrevieja, Alicante",
  "locatedIn": null,
  "plusCode": "X8GC+W8 Torrevieja",
  "website": "lawyersag.com",
  "phone": "965 50 53 05",
  "temporarilyClosed": false,
  "permanentlyClosed": false,
  "rank": 3,
  "placeId": "ChIJoxevz_-pYw0RHxS7mgxaXi8",
  "url": "https://www.google.com/maps/place/A%26G+Lawyers/@37.9772899,-0.6814326,17z/data=!3m1!4b1!4m5!3m4!1s0xd63a9ffcfaf17a3:0x2f5e5a0c9abb141f!8m2!3d37.9772899!4d-0.6792439?hl=en",
  "searchString": "Lawyers",
  "location": {
    "lat": 37.9772899,
    "lng": -0.6792439
  },
  "reviewsCount": 21
}
```
Thank you.

**Comment by metalwarrior665** [comment]
Thanks, might do something with the recent localization update. But who knows, I will check it out.

**Comment by HazelCuate** [comment]
I also noticed this problem in the code from one week ago or so.

**Comment by pocesar** [comment]
@HazelCuate can you provide the settings you using for INPUT of the scraper?

**Comment by HazelCuate** [comment]
Sure.
```
{
  "searchString": "Lawyers",
  "language": "en",
  "maxCrawledPlaces": 250,
  "lat": "37.9144677",
  "lng": "-1.2708565",
  "zoom": 10,
  "maxAutomaticZoomOut": 0,
  "maxConcurrency": 2,
  "maxPageRetries": 3
}
```

**Comment by HazelCuate** [comment]
Hi guys, any idea? Is my config wrong?

**Comment by pocesar** [comment]
doesn't seem to be an issue with neither the localization nor the selector on page. from the tests, there are a lot of items there that don't have any ratings, so it's expected it to be `null`. can you point to one specific item that is wrongly showing the score as null but has a score on page?

**Comment by HazelCuate** [comment]
Yes, sure:
```
{
  "title": "The PUB Praha 2",
  "subTitle": null,
  "totalScore": null,
  "categoryName": "Restaurant",
  "address": "Hálkova 6, 120 00 Nové Město, Czechia",
  "locatedIn": null,
  "plusCode": "3CGH+F8 Prague 2, Czechia",
  "website": "thepub.cz",
  "phone": "+420 222 940 414",
  "temporarilyClosed": false,
  "permanentlyClosed": false,
  "rank": 11,
  "placeId": "ChIJXRQlXoyUC0cRq5R4OBRKKxU",
  "url": "https://www.google.com/maps/place/The+PUB+Praha+2/@50.0761791,14.4261789,17z/data=!3m1!4b1!4m5!3m4!1s0x470b948c5e25145d:0x152b4a14387894ab!8m2!3d50.0761791!4d14.4283676?hl=en",
  "searchString": "pubs near prague",
  "location": {
    "lat": 50.0761791,
    "lng": 14.4283676
  },
  "reviewsCount": 826
}
```
And here is the INPUT.json used:
```
{
  "searchStringsArray": ["pubs near prague"],
  "lat": "50.0860729",
  "lng": "14.4135326",
  "zoom": 10,
  "proxyConfig": { "useApifyProxy": false },
  "maxCrawledPlaces": 20
}
```

**Comment by HazelCuate** [comment]
Hi guys, I don't mean to push you but this bug is preventing me from advancing in a school project I'm doing.

I've been looking at your code but I don't find problem, do you have any idea?

**Comment by HazelCuate** [comment]
Hi, It would be very helpful to just **know** if you guys plan to fix this any time soon, so I can re-think my project in case you don't.

Thanks a lot in any case, this project is awesome.

**Comment by metalwarrior665** [comment]
Hello,

I'm sorry that we didn't get back to you earlier. We just didn't have much time to work on it.

I have spent a day with the scraper and I haven't found a case where it would not scrape `totalScore`, locally or on the platform. I think the issue might be the location. Where are you from? I mean in what language is your browser setup.

**Comment by HazelCuate** [comment]
> I have spent a day with the scraper and I haven't found a case where it would not scrape `totalScore`, locally or on the platform. I think the issue might be the location. Where are you from? I mean in what language is your browser setup.

I use Chrome with the GUI in spanish and the Google sites in english, the language field in my INPUT.json is set to "en" and my Chrome's Accept-Language header field is:
en,en-US;q=0.9,en-GB;q=0.8,es-ES;q=0.7,es;q=0.6,gl;q=0.5

Today I reinstalled my OS and repeated the test with fresh crawler-google-places code and npm dependencies and the results are the same:
```
$ for i in *.json;do python3 -m json.tool "$i" | grep -E 'totalScore|title';done
    "title": "The Pub Pilsner Unique Bar",
    "totalScore": null,
    "title": "Rocky O'Reilly's",
    "totalScore": null,
    "title": "Placebo Bar",
    "totalScore": null,
    "title": "Black Angel's Bar",
    "totalScore": null,
    "title": "Drunken Monkey Prague Pub Crawl",
    "totalScore": null,
    "title": "Hells Bells Rockin' Pub",
    "totalScore": null,
    "title": "J.J. Murphy's Irish Pub",
    "totalScore": null,
    "title": "Prague Beer Museum",
    "totalScore": null,
    "title": "U Kun\u0161t\u00e1t\u016f - Craft Beer In Old Prague",
    "totalScore": null,
    "title": "O'Che's Irish Bar",
    "totalScore": null,
    "title": "The PUB Praha 2",
    "totalScore": null,
    "title": "Golden Tiger",
    "totalScore": null,
    "title": "The James Joyce",
    "totalScore": null,
    "title": "Caffrey's Irish Bar",
    "totalScore": null,
    "title": "Anonymous Bar",
    "totalScore": null,
    "title": "Gastro Bar 1401 Praha",
    "totalScore": null,
    "title": "HANGAR CLUB & BAR PRAGUE",
    "totalScore": null,
    "title": "The Dubliner Irish Bar",
    "totalScore": null,
    "title": "McCarthy's Irish Pub",
    "totalScore": null,
    "title": "The Pub Praha 1",
    "totalScore": null,
```
And here is my INPUT.json:
```
{
  "searchStringsArray": ["pubs near prague"],
  "lat": "50.0860729",
  "lng": "14.4135326",
  "zoom": 10,
  "proxyConfig": { "useApifyProxy": false },
  "maxAutomaticZoomOut": 0,
  "maxCrawledPlaces": 20,
  "maxConcurrency": 3,
  "maxPageRetries": 2,
  "maxReviews": 0,
  "language": "en"
}
```

**Comment by pocesar** [comment]
@metalwarrior665 this seems dependent on the language used, might be related to how the `globalParser.numberParser` works. this, for example, has `totalScore` as null https://www.google.com/maps/place/Docteur+Brault+Nicolas/@48.8658015,2.3989211,17z/data=!3m1!4b1!4m5!3m4!1s0x47e66d0f9b0ad785:0xa8144bae9d444f92!8m2!3d48.8658015!4d2.4011098?hl=fr

**Comment by HazelCuate** [comment]
@metalwarrior665 is there anything I can try to fix this?

Thank you.

**Comment by metalwarrior665** [comment]
I will try to rework this so we grab it from the ugly JSON Google has there somewhere (seems promising) and not rely on the stupid `globalParser`

**Comment by metalwarrior665** [comment]
I pushed a new code, on Apify platform as beta. Can you guys test it?

**Comment by HazelCuate** [comment]
> I pushed a new code, on Apify platform as beta. Can you guys test it?

Yes, It works now.

Thank you!!
