### ISSUE TITLE
option reviewSort not working

### ISSUE THREAD

**Issue by cristeacosmin** [drobnikj/crawler-google-places#96]
Hey,

Although in input I can see the option is sent as intended 

![image](https://user-images.githubusercontent.com/10389279/102187024-1f030f00-3ebc-11eb-9aa1-c94c4cb9fc7a.png)

The option is not applied..

PS: I am running on the apify platform

**Comment by pocesar** [comment]
are you using English as language?

**Comment by cristeacosmin** [comment]
Yes, using english ( default )

**Comment by cristeacosmin** [comment]
any news? is it a bug? am i doing something wrong?

**Comment by metalwarrior665** [comment]
It is a bug. I did a small update and it sort by newest but there are some duplicates. It will require a bigger overhaul.

**Comment by metalwarrior665** [comment]
Should be fixed in beta, latest launched tomorrow
