### ISSUE TITLE
  TypeError: Cannot read property 'includeReviews' of null

### ISSUE THREAD

**Issue by Gwojda** [drobnikj/crawler-google-places#97]
➜  crawler-google-places git:(master) ✗ npm run start

> crawler-google-places@1.0.0 start
> node ./src/main.js

INFO  System info {"apifyVersion":"0.21.10","apifyClientVersion":"0.6.0","osType":"Darwin","nodeVersion":"v15.2.0"}
WARN  Neither APIFY_LOCAL_STORAGE_DIR nor APIFY_TOKEN environment variable is set, defaulting to APIFY_LOCAL_STORAGE_DIR="/private/tmp/crawler-google-places/apify_storage"
ERROR The function passed to Apify.main() threw an exception:
  TypeError: Cannot read property 'includeReviews' of null
      at module.exports.makeInputBackwardsCompatible (/private/tmp/crawler-google-places/src/input-validation.js:12:15)
      at /private/tmp/crawler-google-places/src/main.js:20:5
      at async run (/private/tmp/crawler-google-places/node_modules/apify/build/actor.js:194:13)
npm ERR! code 91
npm ERR! path /private/tmp/crawler-google-places
npm ERR! command failed
npm ERR! command sh -c node ./src/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-12-15T13_45_44_413Z-debug.log

**Comment by metalwarrior665** [comment]
Hello,

I think you didn't pass in any JSON input to the actor. Check the [tutorial](https://sdk.apify.com/docs/guides/quick-start).
