### ISSUE TITLE
Additional data extraction is unstable

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#98]
It works most of the time but sometimes fails to click on the back button, etc. If possible we should try to extract this via XHR.

**Comment by falkenbach** [comment]
At the moment of writing the only additional data is "Web results" as far as I can see (i.e. https://goo.gl/maps/c62MM8kXhWUtnEVW8), need to scroll to bottom to trigger loading

**Comment by metalwarrior665** [comment]
It is not web results. Check the results or code what it is doing. It takes the extra information about the place.

**Comment by metalwarrior665** [comment]
This should now work much better with the buttons but I think it is probably still not perfect

**Comment by yashbabar** [comment]
Seeing that the labels (like women-led or LGBTQ-friendly) aren't being returned with additional info (as shown in the sample result in the documentation).
For eg. https://g.page/ConscienceK?share when fetched through the following:

`{
   "searchStringsArray":[
      "consciencekitchen"
   ],
   "maxCrawledPlaces":0,
   "language":"en",
   "maxReviews":1,
   "maxImages":0,
   "includeHistogram":false,
   "includeOpeningHours":false,
   "includePeopleAlsoSearch":false,
   "additionalInfo":true,
   "reviewsSort":"mostRelevant",
   "reviewsTranslation":"originalAndTranslated",
   "exportPlaceUrls":false,
   "country":"united kingdom",
   "city":"london",
   "proxyConfig":{
      "useApifyProxy":true
   },
   "useChrome":false,
   "debug":false,
   "useStealth":false,
   "scrapeReviewerName":false,
   "scrapeReviewerId":false,
   "scrapeReviewerUrl":false,
   "scrapeReviewId":false,
   "scrapeReviewUrl":false,
   "scrapeResponseFromOwnerText":false,
   "zoom":12,
   "maxConcurrency":100,
   "maxPageRetries":6,
   "pageLoadTimeoutSec":60,
   "maxPagesPerBrowser":1
}` 
returns

`[{
  "title": "Conscience Kitchen",
  "subTitle": null,
  "categoryName": "Restaurant",
  "address": "23 All Saints Rd, London W11 1HE, United Kingdom",
  "locatedIn": null,
  "neighborhood": "23 All Saints Rd",
  "street": "23 All Saints Rd",
  "city": "London",
  "postalCode": "W11 1HE",
  "state": null,
  "countryCode": "GB",
  "plusCode": "GQ9W+79 London, United Kingdom",
  "website": "consciencekitchen.com",
  "phone": "+44 800 710 1108",
  "temporarilyClosed": false,
  "permanentlyClosed": false,
  "totalScore": 4.9,
  "isAdvertisement": false,
  "rank": 1,
  "placeId": "ChIJJ1z2bMERdkgR4O6-p37cdlk",
  "url": "https://www.google.com/maps/place/Conscience+Kitchen/@51.5182451,-0.2063097,17z/data=!3m1!4b1!4m5!3m4!1s0x487611c16cf65c27:0x5976dc7ea7beeee0!8m2!3d51.5182489!4d-0.2041088?hl=en",
  "searchPageUrl": "https://www.google.com/maps/search/consciencekitchen/@51.489304,-0.2245179,12z?hl=en",
  "searchString": "consciencekitchen",
  "location": {
    "lat": 51.5182489,
    "lng": -0.2041088
  },
  "scrapedAt": "2021-05-29T05:42:42.934Z",
  "reviewsCount": 34,
  "reviewsDistribution": {
    "oneStar": 0,
    "twoStar": 0,
    "threeStar": 2,
    "fourStar": 1,
    "fiveStar": 31
  },
  "reviews": [
    {
      "name": null,
      "text": "new food menu is just fab!\npoke and salmon on rice... mmmm... very delicious!\ncoffee is always great, smooth.\nHighly recommended!",
      "publishAt": "2 days ago",
      "publishedAtDate": "2021-05-26T12:22:26.975Z",
      "likesCount": null,
      "reviewId": null,
      "reviewUrl": null,
      "reviewerId": null,
      "reviewerUrl": null,
      "reviewerNumberOfReviews": 18,
      "isLocalGuide": false,
      "stars": 5,
      "rating": null,
      "responseFromOwnerDate": null,
      "responseFromOwnerText": null
    }
  ],
  "orderBy": [
    {
      "name": "consciencekitchen.com",
      "url": "https://www.consciencekitchen.com/online-ordering"
    },
    {
      "name": "deliveroo.co.uk",
      "url": "https://deliveroo.co.uk/menu/london/notting-hill/conscience-kitchen-london?utm_medium=affiliate&utm_source=google_maps_link"
    }
  ]
}]`

**Comment by yashbabar** [comment]
This seems to work now with the latest patch 👍 Thanks!

**Comment by metalwarrior665** [comment]
@yashbabar This issue was created for a different problem that scraping it mostly worked but in like 2% of places the scraper was not able to click through.

The last patch addressed the redesign from Google that made it not work at all.

So I want to keep this issue opened but hopefully we won't be seeing it much (or at all).

**Comment by yashbabar** [comment]
Thanks! Appreciate all your work.

**Comment by metalwarrior665** [comment]
I think it is quite stable now
